# Generated by Django 2.2.3 on 2019-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ass13',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('cource', models.CharField(max_length=30)),
                ('cno', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
