# Generated by Django 2.0.1 on 2019-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0002_auto_20190826_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ass13',
            name='cno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
