# Generated by Django 2.2.7 on 2020-06-14 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0002_remove_retrivedata_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retrivedata',
            old_name='task_description',
            new_name='blog_description',
        ),
        migrations.RenameField(
            model_name='retrivedata',
            old_name='task_name',
            new_name='blog_name',
        ),
        migrations.RemoveField(
            model_name='retrivedata',
            name='No_of_hours',
        ),
        migrations.RemoveField(
            model_name='retrivedata',
            name='task_creationdate',
        ),
        migrations.RemoveField(
            model_name='retrivedata',
            name='task_enddate',
        ),
        migrations.RemoveField(
            model_name='retrivedata',
            name='task_startdate',
        ),
        migrations.RemoveField(
            model_name='retrivedata',
            name='task_updatedate',
        ),
        migrations.AddField(
            model_name='retrivedata',
            name='ur_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
