# Generated by Django 2.2.7 on 2020-06-15 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0003_auto_20200614_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tododata',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='tododata',
            old_name='password',
            new_name='passwordo',
        ),
        migrations.AddField(
            model_name='tododata',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tododata',
            name='passwordt',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tododata',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
