# Generated by Django 2.2.3 on 2019-08-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ass13',
            old_name='cource',
            new_name='course',
        ),
    ]
